#!/bin/bash

domain="moul.io"
rootdir="public"

create_package() {
    project_name="$1"
    project_url="$2"
    is_private="$3"

    # Only add to public listing if not private
    if [ "$is_private" != "yes" ]; then
        echo "$project_name" >> $rootdir/go-packages.txt
    fi
    
    # Always create the go-get redirect and pages (even for private repos)
    echo "/$project_name/* go-get=1 /$project_name/go-get.html 200!" >> $rootdir/_redirects
    #echo "/$project_name/ $project_url 301!" >> $rootdir/_redirects
    #echo "/$project_name/* $project_url 301!" >> $rootdir/_redirects

    mkdir -p $rootdir/$project_name
    cat > $rootdir/$project_name/go-get.html <<EOF
<html><head>
    <meta name="go-import" content="$domain/$project_name git $project_url">
    <meta name="go-source" content="$domain/$project_name     $project_url $project_url/tree/master{/dir} $project_url/tree/master{/dir}/{file}#L{line}">
</head></html>
EOF
    cat > $rootdir/$project_name/index.html <<EOF
<html>
  <head>
    <title>$domain/$project_name</title>
    <link rel="stylesheet" type="text/css" href="/style.css">
    <meta property="og:title" content="$domain/$project_name Go module">
    <meta property="og:type" content="article">
    <meta property="og:author" content="article">
    <meta property="og:url" content="https://$domain/$project_name">
    <meta property="og:image" content="https://$domain/moul-codes.png">
    <meta property="og:site_name" content="$domain">
    <meta property="article:author" content="https://manfred.life">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#9f00a7">
    <meta name="theme-color" content="#ffffff">
  </head>
  <body>
    <h1>$domain/$project_name</h1>
    <pre><code>go get $domain/$project_name</code></pre>
    <pre><code>import "$domain/$project_name"</code></pre>
    Home: <a href="$project_url">$project_url</a><br />
    Doc: <a href="https://pkg.go.dev/$domain/$project_name">https://pkg.go.dev/$domain/$project_name</a>
    <script async defer src="https://sa.moul.io/latest.js"></script>
    <noscript><img src="https://sa.moul.io/noscript.gif" alt="" referrerpolicy="no-referrer-when-downgrade" /></noscript>
  </body>
</html>
EOF

}

# Skip header line and process CSV
tail -n +2 vanity.csv | while IFS=',' read -r project_name project_url is_private; do
    if [ -z "$project_name" ]; then continue; fi
    create_package "$project_name" "$project_url" "$is_private"
done

cat $rootdir/go-packages.txt | sort -u > $rootdir/go-packages-sorted.txt
mv $rootdir/go-packages-sorted.txt $rootdir/go-packages.txt

# generate root index.html
cat > $rootdir/index.html <<EOF
<html>
  <head>
    <title>$domain Go modules</title>
    <link rel="stylesheet" type="text/css" href="/style.css">
    <meta property="og:title" content="$domain Go modules">
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://$domain/">
    <meta property="og:image" content="https://$domain/moul-codes.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#9f00a7">
    <meta name="theme-color" content="#ffffff">
  </head>
  <body>
    <h1>$domain Go Modules</h1>
    <ul>
EOF
while read line; do
    echo '        <li><a href="'./$line/'">'$domain/$line'</a></li>' >> $rootdir/index.html
done < $rootdir/go-packages.txt
cat >> $rootdir/index.html <<EOF
      </ul>
      <hr />
      Generated by <a href="https://github.com/moul/moul.io">github.com/moul/moul.io</a>.
      <script async defer src="https://sa.moul.io/latest.js"></script>
      <noscript><img src="https://sa.moul.io/noscript.gif" alt="" referrerpolicy="no-referrer-when-downgrade" /></noscript>
   </body>
</html>
EOF
